---
- name: BACKUP IOS CONFIGURATION
  hosts: all
  gather_facts: no
  
  tasks:
  - name: backup the configuration to tower
    ios_config:
      backup: yes
    register: backup
    
  - name: show backup location and file name
    debug:
      var: backup.backup_path
