---
- name: BACKUP IOS CONFIGURATION
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: backup the configuration
    ios_config:
      backup: yes
    register: backup
    
  - name: show backup_path
    debug:
      var: backup.backup_path
    
  - name: remove building configuration line
    lineinfile:
      path: backup.backup_path
      line: "Building configuration..."
      state: absent
   
  - name: remove current configuration line
    lineinfile:
      path: backup.backup_path
      line: 'Current configuration.*'
      state: absent
