---
- name: BACKUP CONFIGURATION
  hosts: all
  gather_facts: no
  connection: local
  
  tasks:
  - name: backup the configuration to var backup
    ios_config:
      backup: yes
    register: backup
    
  - name: show config
    debug:
      var: backup
