---
- name: ENABLE SWITCH PORT
  hosts: "{{ ios_host }}"
  gather_facts: no
  
  tasks:
    - name: "apply 'no shutdown' command to {{ ios_interface }} on {{ ios_host }}"
      ios_config:
        lines:
          - no shutdown
        parents: interface {{ ios_interface }}
