---
- name: GET CISCO BASE INFORMATION
  hosts: all
  gather_facts: no

  tasks:
    - name: gather information
      ios_command:
        commands:
          - show version | include IOS
          - show ip interface brief
      register: output

    - name: display information
      debug:
        var: output.stdout_lines
