---
- name: GENERATE INTERFACE REPORT
  hosts: all
  gather_facts: no
  connection: network_cli
  
  roles:
    - ansible-network.network-engine
    
  tasks:
    - name: capture show interfaces
      ios_command:
        commands:
          - show interfaces
      register:  output
      
    - name: parse the raw output
      command_parser:
        file: "parsers/show_interfaces.yml"
        content: "{{ output.stdout[0] }}"
