---
- hosts: all
  gather_facts: no

# {{vlan}} & {{ interface }} input  will be passed through template extra variables

  tasks:
     - name: "Create VLAN {{ vlan }}"
       ios_vlan:
         vlan_id: "{{ vlan }}"
         name: test-vlan
         state: present

     - name: "Configure interface {{ interface }}"
       ios_vlan:
         vlan_id: "{{ vlan }}"
         interfaces:
           - "{{ interface }}"
           
     - name: "Verify {{ interface }}"
       ios_command:
         commands: 
           - show run int {{ interface }}          
       register: int

     - debug: 
         var: int.stdout_lines  
