---
- name: CREATE VLAN AND ADD INTERFACE
  hosts: all
  gather_facts: no

# set {{ vlan }} & {{ interface }} variables in template extra variables

  tasks:
     - name: "Create VLAN {{ vlan }}"
       ios_vlan:
         vlan_id: "{{ vlan }}"
         name: test-vlan
         state: present

     - name: "Configure interface {{ interface }}"
       ios_vlan:
         vlan_id: "{{ vlan }}"
         interfaces: "{{ interface }}"
           
     - name: "Verify {{ interface }}"
       ios_command:
         commands: 
           - show run int {{ interface }}          
       register: int

     - debug: 
         var: int.stdout_lines
         
     - name: Copy running config to startup config
       ios_command:
         authorize: yes
         commands:
           - copy run start
